name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ijn35807/docker-image-autobuild:latest
    - name: Push Docker image
      run: docker login -u imranpst -p ${{ secrets.DOCKER_SECRET }} && docker push imranpst/test:1.0.0
